
env:
   global:
     - CONAN_REFERENCE: "SOCI/4.0.0"
     - CONAN_USERNAME: "user"
     - CONAN_LOGIN_USERNAME: "user"
     - CONAN_CHANNEL: "channel"
     - CONAN_BUILD_POLICY: "missing"
     - CONAN_REMOTES: "https://api.bintray.com/conan/bincrafters/public-conan"

services:
  - mysql
  - postgresql

addons:
  postgresql: "10"
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
      - postgresql-10
      - postgresql-client-10
      - postgresql-server-dev-10

linux: &linux
   os: linux
   dist: xenial
   sudo: required
   language: python
   python: "3.6"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:

      - <<: *linux
        env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=conanio/gcc49

      - <<: *linux
        env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=conanio/gcc5

      - <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=conanio/gcc6

      - <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=conanio/gcc7

      - <<: *linux
        env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8

      - <<: *linux
        env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=conanio/clang39

      - <<: *linux
        env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=conanio/clang40

      - <<: *linux
        env: CONAN_CLANG_VERSIONS=5.0 CONAN_DOCKER_IMAGE=conanio/clang50

      - <<: *linux
        env: CONAN_CLANG_VERSIONS=6.0 CONAN_DOCKER_IMAGE=conanio/clang60

      - <<: *linux
        env: CONAN_CLANG_VERSIONS=7.0 CONAN_DOCKER_IMAGE=conanio/clang7

      - <<: *osx
        osx_image: xcode7.3
        env: CONAN_APPLE_CLANG_VERSIONS=7.3

      - <<: *osx
        osx_image: xcode8.3
        env: CONAN_APPLE_CLANG_VERSIONS=8.1

      - <<: *osx
        osx_image: xcode9.2
        env: CONAN_APPLE_CLANG_VERSIONS=9.0

      - <<: *osx
        osx_image: xcode9.3
        env: CONAN_APPLE_CLANG_VERSIONS=9.1

      - <<: *osx
        osx_image: xcode10
        env: CONAN_APPLE_CLANG_VERSIONS=10.0

before_install:
  # MySQL 5.7: reset password
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('mysql_root_pass') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -pmysql_root_pass
  - sudo service mysql restart
  # MySQL setup
  - mysql -u root -pmysql_root_pass -e "CREATE DATABASE IF NOT EXISTS conan_soci_test;"
  - mysql -u root -pmysql_root_pass -e "CREATE USER 'conan_soci_user'@'localhost' IDENTIFIED BY PASSWORD 'conan_soci_pass';"
  - mysql -u root -pmysql_root_pass -e "GRANT ALL ON stockmarket.* TO 'conan_soci_user'@'localhost';"
  # PostgreSQL setup
  - psql -U postgres -c "CREATE DATABASE conan_soci_test;"
  - psql -U postgres -c "CREATE USER 'conan_soci_user' WITH PASSWORD 'conan_soci_pass';"
  - psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE conan_soci_test to conan_soci_user;"

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
