build: false

environment:
    PYTHON: "C:\\Python37"

    CONAN_REFERENCE: "SOCI/4.0.0"
    CONAN_USERNAME: "user"
    CONAN_LOGIN_USERNAME: "user"
    CONAN_CHANNEL: "channel"
    CONAN_BUILD_POLICY: "missing"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 12
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15

platform:
  - Win32
  - x64

configuration:
  - Release

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools
  - conan user # It creates the conan data directory
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

test_script:
  - conan create . %CONAN_USERNAME%/%CONAN_CHANNEL%
