build: false

services:
  - mysql
  - postgresql101

environment:
    PYTHON: "C:\\Python37"

    CONAN_REFERENCE: "SOCI/4.0.0"
    CONAN_USERNAME: "user"
    CONAN_LOGIN_USERNAME: "user"
    CONAN_CHANNEL: "channel"
    CONAN_BUILD_POLICY: "missing"
    CONAN_REMOTES: "https://api.bintray.com/conan/bincrafters/public-conan"
    CONAN_BUILD_TYPES: "Release,Debug"
    CONAN_ARCHS: "x86_64"

    MYSQL_HOST: 127.0.0.1
    MYSQL_PORT: 3306
    MYSQL_USER: root
    MYSQL_PASSWORD: Password12!
    MYSQL_PATH: C:\Program Files\MySQL\MySQL Server 5.7

    POSTGRESQL_HOST: 127.0.0.1
    POSTGRESQL_PORT: 5432
    POSTGRESQL_USER: postgres
    POSTGRESQL_PASSWORD: Password12!
    POSTGRESQL_PATH: C:\Program Files\PostgreSQL\9.4

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 12
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools
  - conan user # It creates the conan data directory

before_build:
  - |-
    "%MYSQL_PATH%\bin\mysql" -h %MYSQL_HOST% -P %MYSQL_PORT% -u %MYSQL_USER% -p"%MYSQL_PASSWORD%" -e "CREATE DATABASE IF NOT EXISTS conan_soci_test;"
  - |-
    "%MYSQL_PATH%\bin\mysql" -h %MYSQL_HOST% -P %MYSQL_PORT% -u %MYSQL_USER% -p"%MYSQL_PASSWORD%" -e "CREATE USER 'conan_soci_user'@'localhost' IDENTIFIED BY PASSWORD 'conan_soci_pass';"
  - |-
    "%MYSQL_PATH%\bin\mysql" -h %MYSQL_HOST% -P %MYSQL_PORT% -u %MYSQL_USER% -p"%MYSQL_PASSWORD%" -e "GRANT ALL ON stockmarket.* TO 'conan_soci_user'@'localhost';"
  - |-
    SET PGPASSWORD=%POSTGRESQL_PASSWORD%
  - |-
    "%POSTGRESQL_PATH%\bin\psql" -h %POSTGRESQL_HOST% -p %POSTGRESQL_PORT% -U %POSTGRESQL_USER% -c "CREATE DATABASE conan_soci_test;"
  - |-
    "%POSTGRESQL_PATH%\bin\psql" -h %POSTGRESQL_HOST% -p %POSTGRESQL_PORT% -U postgres -c "CREATE USER 'conan_soci_user' WITH PASSWORD 'conan_soci_pass';"
  - |-
    "%POSTGRESQL_PATH%\bin\psql" -h %POSTGRESQL_HOST% -p %POSTGRESQL_PORT% -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE conan_soci_test to conan_soci_user;"

test_script:
  - python build.py
